export const ROUTING_RMQ = {
  USER_CREATED: 'user.created',
  USER_MAKE_FRIEND: 'user.makeFriend',
  USER_UPDATE_STATUS_MAKE_FRIEND: 'user.updateStatusMakeFriend',
  NOTIFICATION_CREATED: 'notification.created',
  CONVERSATION_CREATED: 'conversation.created',
  MESSAGE_SENT: 'message.sent',
  MESSAGE_SEND: 'message.send',
  MEMBER_ADDED_TO_CONVERSATION: 'member.addedToConversation',
  USER_UPDATED: 'user.updated',
  CALL_STARTED: 'call.started',
  CALL_ACCEPTED: 'call.accepted',
  CALL_REJECTED: 'call.rejected',
  CALL_ENDED: 'call.ended',
  CALL_PARTICIPANT_JOINED: 'call.participant.joined',
  CALL_PARTICIPANT_LEFT: 'call.participant.left',
}
