// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.4
// source: chat.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

export enum ConversationAssetKind {
  ASSET_MEDIA = 0,
  ASSET_LINK = 1,
  ASSET_DOC = 2,
  UNRECOGNIZED = -1,
}

export enum MessageType {
  TEXT = 0,
  IMAGE = 1,
  VIDEO = 2,
  FILE = 3,
  UNRECOGNIZED = -1,
}

export enum MediaType {
  MEDIA_IMAGE = 0,
  MEDIA_VIDEO = 1,
  MEDIA_FILE = 2,
  UNRECOGNIZED = -1,
}

export interface MessageMedia {
  id: string;
  messageId: string;
  mediaType: MediaType;
  objectKey: string;
  url: string;
  mimeType: string;
  size: string;
  width?: number | undefined;
  height?: number | undefined;
  duration?: number | undefined;
  thumbnailUrl?: string | undefined;
  sortOrder: number;
}

export interface Member {
  username: string;
  avatar?: string | undefined;
  userId: string;
  lastReadAt?: string | undefined;
  fullName?: string | undefined;
}

export interface CreateConversationRequest {
  type: string;
  members: Member[];
  groupName?: string | undefined;
  groupAvatar?: Uint8Array | undefined;
  groupAvatarFilename?: string | undefined;
  createrId?: string | undefined;
}

export interface CreateConversationResponse {
  conversation: Conversation | undefined;
}

export interface AddMemberToConversationRequest {
  conversationId: string;
  members: Member[];
  userId: string;
}

export interface AddMemberToConversationResponse {
  status: string;
}

export interface GetConversationsRequest {
  userId: string;
  limit: string;
  cursor: string;
}

export interface Message {
  id: string;
  conversationId: string;
  senderId: string;
  text: string;
  replyToMessageId?: string | undefined;
  isDeleted: boolean;
  deleteType: string;
  createdAt: string;
  senderMember: SenderMember | undefined;
  type: MessageType;
  clientMessageId?: string | undefined;
  medias: MessageMedia[];
}

export interface ConversationMember {
  userId: string;
  /** timestamp (ms) */
  lastReadAt?: string | undefined;
  username?: string | undefined;
  avatar?: string | undefined;
  lastReadMessageId?: string | undefined;
  fullName?: string | undefined;
  lastMessageAt: string;
}

export interface Conversation {
  id: string;
  type: string;
  unreadCount: string;
  groupName?: string | undefined;
  groupAvatar?: string | undefined;
  createdAt: string;
  updatedAt?: string | undefined;
  members: ConversationMember[];
  lastMessage?: Message | undefined;
}

export interface GetConversationsResponse {
  conversations: Conversation[];
}

export interface GetMessagesRequest {
  conversationId: string;
  userId: string;
  limit: string;
  page: string;
  cursor?: string | undefined;
}

export interface SenderMember {
  userId: string;
  username: string;
  avatar: string;
  fullName?: string | undefined;
}

export interface GetMessagesResponse {
  messages: Message[];
}

export interface GetConversationAssetsRequest {
  conversationId: string;
  userId: string;
  kind: ConversationAssetKind;
  limit: string;
  cursor?: string | undefined;
}

export interface GetConversationAssetsResponse {
  messages: Message[];
  nextCursor?: string | undefined;
}

export interface SendMessageRequest {
  conversationId: string;
  message?: string | undefined;
  senderId: string;
  replyToMessageId?: string | undefined;
  type: MessageType;
  medias: SendMessageMediaInput[];
  clientMessageId?: string | undefined;
}

export interface SendMessageMediaInput {
  mediaType: MediaType;
  objectKey: string;
  url: string;
  mimeType: string;
  size: string;
  width?: number | undefined;
  height?: number | undefined;
  duration?: number | undefined;
  thumbnailUrl?: string | undefined;
  sortOrder: number;
}

export interface SendMessageResponse {
  message: Message | undefined;
}

export interface CreateMessageUploadUrlRequest {
  conversationId: string;
  userId: string;
  type: MessageType;
  mimeType: string;
  fileName: string;
  size: string;
}

export interface CreateMessageUploadUrlResponse {
  uploadUrl: string;
  objectKey: string;
  publicUrl: string;
  expiresInSeconds: string;
}

export interface ReadMessageRequest {
  conversationId: string;
  lastReadMessageId: string;
  userId: string;
}

export interface ReadMessageResponse {
  lastReadMessageId: string;
}

export interface SearchConversationRequest {
  userId: string;
  keyword: string;
}

export interface SearchConversationResponse {
  conversations: Conversation[];
}

export interface GetConversationByFriendIdRequest {
  friendId: string;
  userId: string;
}

export interface GetConversationByFriendIdResponse {
  conversation: Conversation | undefined;
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatGrpcServiceClient {
  createConversation(request: CreateConversationRequest, metadata?: Metadata): Observable<CreateConversationResponse>;

  addMemberToConversation(
    request: AddMemberToConversationRequest,
    metadata?: Metadata,
  ): Observable<AddMemberToConversationResponse>;

  getConversations(request: GetConversationsRequest, metadata?: Metadata): Observable<GetConversationsResponse>;

  getMessagesByConversationId(request: GetMessagesRequest, metadata?: Metadata): Observable<GetMessagesResponse>;

  getConversationAssets(
    request: GetConversationAssetsRequest,
    metadata?: Metadata,
  ): Observable<GetConversationAssetsResponse>;

  sendMessage(request: SendMessageRequest, metadata?: Metadata): Observable<SendMessageResponse>;

  createMessageUploadUrl(
    request: CreateMessageUploadUrlRequest,
    metadata?: Metadata,
  ): Observable<CreateMessageUploadUrlResponse>;

  readMessage(request: ReadMessageRequest, metadata?: Metadata): Observable<ReadMessageResponse>;

  searchConversations(request: SearchConversationRequest, metadata?: Metadata): Observable<SearchConversationResponse>;

  getConversationByFriendId(
    request: GetConversationByFriendIdRequest,
    metadata?: Metadata,
  ): Observable<GetConversationByFriendIdResponse>;
}

export interface ChatGrpcServiceController {
  createConversation(
    request: CreateConversationRequest,
    metadata?: Metadata,
  ): Promise<CreateConversationResponse> | Observable<CreateConversationResponse> | CreateConversationResponse;

  addMemberToConversation(
    request: AddMemberToConversationRequest,
    metadata?: Metadata,
  ):
    | Promise<AddMemberToConversationResponse>
    | Observable<AddMemberToConversationResponse>
    | AddMemberToConversationResponse;

  getConversations(
    request: GetConversationsRequest,
    metadata?: Metadata,
  ): Promise<GetConversationsResponse> | Observable<GetConversationsResponse> | GetConversationsResponse;

  getMessagesByConversationId(
    request: GetMessagesRequest,
    metadata?: Metadata,
  ): Promise<GetMessagesResponse> | Observable<GetMessagesResponse> | GetMessagesResponse;

  getConversationAssets(
    request: GetConversationAssetsRequest,
    metadata?: Metadata,
  ): Promise<GetConversationAssetsResponse> | Observable<GetConversationAssetsResponse> | GetConversationAssetsResponse;

  sendMessage(
    request: SendMessageRequest,
    metadata?: Metadata,
  ): Promise<SendMessageResponse> | Observable<SendMessageResponse> | SendMessageResponse;

  createMessageUploadUrl(
    request: CreateMessageUploadUrlRequest,
    metadata?: Metadata,
  ):
    | Promise<CreateMessageUploadUrlResponse>
    | Observable<CreateMessageUploadUrlResponse>
    | CreateMessageUploadUrlResponse;

  readMessage(
    request: ReadMessageRequest,
    metadata?: Metadata,
  ): Promise<ReadMessageResponse> | Observable<ReadMessageResponse> | ReadMessageResponse;

  searchConversations(
    request: SearchConversationRequest,
    metadata?: Metadata,
  ): Promise<SearchConversationResponse> | Observable<SearchConversationResponse> | SearchConversationResponse;

  getConversationByFriendId(
    request: GetConversationByFriendIdRequest,
    metadata?: Metadata,
  ):
    | Promise<GetConversationByFriendIdResponse>
    | Observable<GetConversationByFriendIdResponse>
    | GetConversationByFriendIdResponse;
}

export function ChatGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createConversation",
      "addMemberToConversation",
      "getConversations",
      "getMessagesByConversationId",
      "getConversationAssets",
      "sendMessage",
      "createMessageUploadUrl",
      "readMessage",
      "searchConversations",
      "getConversationByFriendId",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_GRPC_SERVICE_NAME = "ChatGrpcService";
