export const mockUsers = [
  {
    id: '1',
    name: 'Yong Tonghyon',
    avatar: '/thoughtful-asian-man.png',
    lastMessage: 'What makes it different from ...',
    timestamp: '11:32 AM',
    unreadCount: 2,
    status: 'Last seen recently',
    bio: 'Life is mirror, smile at it 😊',
    phone: '6462662535',
  },
  {
    id: '2',
    name: 'Sarah Miller',
    avatar: '/woman-red-shirt.jpg',
    lastMessage: 'The project deadline is approachin...',
    timestamp: '10:45 AM',
    status: 'Last seen recently',
    bio: 'Product Designer | Creative Thinker',
    phone: '5551234567',
  },
  {
    id: '3',
    name: 'David Chen',
    avatar: '/asian-man-suit.jpg',
    lastMessage: 'Can we schedule a meeting f...',
    timestamp: '9:20 AM',
    unreadCount: 3,
    status: 'Online',
    isOnline: true,
  },
  {
    id: '4',
    name: 'Emma Thompson',
    avatar: '/blonde-woman-portrait.png',
    lastMessage: 'I reviewed the proposal and...',
    timestamp: '8:15 AM',
    status: 'Last seen 2 hours ago',
  },
  {
    id: '5',
    name: 'James Wilson',
    avatar: '/man-glasses.png',
    lastMessage: 'The client loved our presentation!',
    timestamp: 'Yesterday',
    status: 'Last seen yesterday',
  },
  {
    id: '6',
    name: 'Sophia Garcia',
    avatar: '/smiling-hispanic-woman.png',
    lastMessage: 'Lets finalize the design tomor...',
    timestamp: 'Yesterday',
    unreadCount: 1,
    status: 'Last seen yesterday',
  },
  {
    id: '7',
    name: 'Lucas Brown',
    avatar: '/man-with-beard.png',
    lastMessage: 'The new features are ready for test',
    timestamp: 'Monday',
    status: 'Last seen Monday',
  },
  {
    id: '8',
    name: 'Isabella Martinez',
    avatar: '/woman-dark-hair.jpg',
    lastMessage: 'Great work on the latest release!',
    timestamp: 'Sunday',
    status: 'Last seen Sunday',
  },
  {
    id: '9',
    name: 'Alice Chen',
    avatar: '/asian-woman-professional.png',
    lastMessage: '',
    timestamp: '',
    status: 'Online',
    isOnline: true,
  },
  {
    id: '10',
    name: 'Bob Smith',
    avatar: '/casual-man.png',
    lastMessage: '',
    timestamp: '',
    status: 'Online',
    isOnline: true,
  },
  {
    id: '11',
    name: 'Carol Johnson',
    avatar: '/business-woman.png',
    lastMessage: '',
    timestamp: '',
    status: 'Last seen recently',
  },
  {
    id: '12',
    name: 'Jelena Denisova',
    avatar: '/professional-woman-portrait.png',
    lastMessage: '',
    timestamp: '',
    status: 'Last seen recently',
    bio: 'Life is mirror, smile at it 😊',
    phone: '6462662535',
  },
]

export const mockMessages: Record<string, unknown[]> = {
  '1': [
    {
      id: '1',
      content: 'Check this out https://short.ly/ghiz82k',
      timestamp: '10:45 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '2',
      content: 'Video call ended · 13m 40s',
      timestamp: '',
      isMine: false,
      type: 'system',
    },
    {
      id: '3',
      content: 'Have you seen the latest updates?',
      timestamp: '10:55 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '4',
      content: 'Nope. Can you please upload it here?',
      timestamp: '10:56 AM',
      isMine: true,
      type: 'text',
    },
    {
      id: '5',
      content: '',
      timestamp: '10:57 AM',
      isMine: false,
      type: 'file',
      fileData: {
        name: 'CryptoCoin-Release.pdf',
        size: '12 mb',
      },
    },
    {
      id: '6',
      content: "Wait. I'm looking into it!",
      timestamp: '10:58 AM',
      isMine: true,
      type: 'text',
    },
  ],
  '2': [
    {
      id: '1',
      content: 'Check this out https://short.ly/ghiz82k',
      timestamp: '10:45 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '2',
      content: 'Video call ended · 13m 40s',
      timestamp: '',
      isMine: false,
      type: 'system',
    },
    {
      id: '3',
      content: 'Have you seen the latest updates?',
      timestamp: '10:55 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '4',
      content: 'Nope. Can you please upload it here?',
      timestamp: '10:56 AM',
      isMine: true,
      type: 'text',
    },
    {
      id: '5',
      content: '',
      timestamp: '10:57 AM',
      isMine: false,
      type: 'file',
      fileData: {
        name: 'CryptoCoin-Release.pdf',
        size: '12 mb',
      },
    },
    {
      id: '6',
      content: "Wait. I'm looking into it!",
      timestamp: '10:58 AM',
      isMine: true,
      type: 'text',
    },
  ],
  '12': [
    {
      id: '1',
      content: '',
      timestamp: '10:57 AM',
      isMine: false,
      type: 'file',
      fileData: {
        name: 'CryptoCoin-Release.pdf',
        size: '12 mb',
      },
    },
    {
      id: '2',
      content: 'Let me know if it works or not?',
      timestamp: '11:11 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '3',
      content: "Wait. I'm looking into it!",
      timestamp: '11:12 AM',
      isMine: true,
      type: 'text',
    },
    {
      id: '4',
      content: 'I checked it. Yep, that works!',
      timestamp: '11:13 AM',
      isMine: true,
      type: 'text',
    },
    {
      id: '5',
      content: "Perfect! I'll prepare the next phase then.",
      timestamp: '11:14 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '6',
      content: "Sounds good. When do you think it'll be ready?",
      timestamp: '11:15 AM',
      isMine: true,
      type: 'text',
    },
    {
      id: '7',
      content: 'Should be done by tomorrow morning.',
      timestamp: '11:15 AM',
      isMine: false,
      type: 'text',
    },
    {
      id: '8',
      content: 'Great! Looking forward to it.',
      timestamp: '11:16 AM',
      isMine: true,
      type: 'text',
    },
  ],
}
